name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./api-v2

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}           # 這個還是看根目錄
          pwd                                  # 會顯示目前工作目錄
          ls .                                 

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 安装依赖
        run: npm ci

      - name: 安裝最新 TypeScript（覆蓋專案版本）
        run: npm install --save-dev typescript@latest

      - name: 编译 TypeScript（生成 dist）
        run: npx tsc

      - name: 运行测试
        run: npm test