name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api-v2

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 安装依赖
        run: npm ci

      - name: 编译 TypeScript（生成 dist）
        run: npx tsc

      - name: 检查 dist 文件夹是否生成
        run: |
          ls -la dist/
          echo "編譯完成！"

      - name: 运行测试（针对 dist 里的 JS 文件）
        run: npm test